### ISSUE TITLE
EPIC 1 User story #1 Set up a basic express application 

### ISSUE THREAD

**Issue by Sambambamm** [SchoolOfCode/bc17-w4d2-project-man-down#1]
```[tasklist]
### Tasks
- [x] Install express by using (NPM install express)
- [x] Create a npm in our project by using (NPM init -y)
- [x] ReadMe detailing how to run and install the application
- [x] Create a js file and start a script in the json file that uses node to run that js file
- [x] import and export the files from JSON and JS to go into a file code app.js
- [x] In the app,js add the express npm by using (install express etc.)
- [x] Create variables that grab express, bind express to work with a function and one that links to our localHost(3000)
- [x] Create a GET request that will show hello world when './ ' is passed using a req and a respond parameter.
- [x] Get the app.js file to listen to our local port(3000)
```
