### ISSUE TITLE
EPIC 2 Implement functionality to GET all activities for a particular user

### ISSUE THREAD

**Issue by Sambambamm** [SchoolOfCode/bc17-w4d2-project-man-down#3]
```[tasklist]
### Tasks
- [x] create an array with multiple objects
- [x] create a function that takes in the get request and outputs the array with multiple objects
- [x] create a cache function that takes in error(400) and outputs error message.
```

**Comment by Irenalou3** [comment]
send a POST request with a JSON request body.
