### ISSUE TITLE
Epic 2 User Story #2 Implement functionality to POST a new activity.

### ISSUE THREAD

**Issue by Irenalou3** [SchoolOfCode/bc17-w4d2-project-man-down#4]
```[tasklist]
### Tasks
- [x] Create a post request containing a JSON object
- [x] Save the posted object into the activites.json fie and give it a unique id
- [x] Submit a timestamp
- [x] When request succeeds show ciorrect status code and the posted object
- [x] when I get invaid post requests show error status code
```
