### ISSUE TITLE
EPIC 3 user story 1(Create functionality for a delete request)

### ISSUE THREAD

**Issue by Sambambamm** [SchoolOfCode/bc17-w4d2-project-man-down#5]
```[tasklist]
### Tasks
- [x] define where the delete will happen
- [x] add a string letting user know what they are deleting
- [x] use our read function to grab data
- [x] specify that we want to remove the id
- [x] delete the id
```
